bin.includes = META-INF/,\
               libsapjco3.so,\
               os4apilib.so,\
               libicudata57.so,\
               libicui18n57.so,\
               libicuuc57.so,\
               libpathextension.so
